package com.itis.secondcourseitis

object WindowRepository {
    val windows = arrayListOf(
        Window(0, "awning window", "rectangle", "https://www.minnkotawindows.com/uploads/photo/awning05.jpg"),
        Window(1, "bay window", "3 windows in semicircle", "https://www.coralwindows.co.uk/wp-content/uploads/2020/03/DSC0612-1.jpg"),
        Window(2, "bow window", "4 windows in semicircle", "https://media.istockphoto.com/photos/bay-window-with-copper-roof-on-traditional-brick-home-with-flowers-picture-id1146950576?k=20&m=1146950576&s=612x612&w=0&h=CRYprCinb2GRDg5peHSVGJKxZWj2wo01YkLBiiRvZkY="),
        Window(3, "casement window", "earliest form of movable window, wood or metal framed, with hinges or pivots at the upright side of the vertically hung sash (ставни)", "https://www.milgard.com/sites/default/files/styles/two_columns_grid_image/public/general_cms/photo-grid-image/photogrids_2col_casement-tuscany.jpg?itok=hwV3vSdj"),
        Window(4, "cottage window", "with two sashes sliding up and down, hung with one atop the other in the same frame", "https://www.anglianhome.co.uk/-/media/ahi/product-catalogue/windows/products/windows-cottage-upvc/gallery/traditional-white-upvc-casement-window-cottage-bars.jpg"),
        Window(5, "center pivot window", "when open, have the sash rotating in the centre of the frame, half in and half out of the room", "https://st.hzcdn.com/fimgs/pictures/hallways/park-slope-brownstone-2-ben-herzog-img~d8011caa00ec79a9_7958-1-1ec7369-w312-h312-b0-p0.jpg"),
        Window(6, "dormer window", "projects vertically from a sloping roof", "https://cdn.vox-cdn.com/thumbor/QnC8tfg-GbaOa8RBvMMYbK3qaFs=/1400x1050/filters:format(jpeg)/cdn.vox-cdn.com/uploads/chorus_asset/file/19509144/dormer_windows_x.jpg"),
        Window(7, "double-hung window", "two operable sashes that slide up and down", "https://modernize.com/wp-content/uploads/2015/10/double-hung-windows.jpg"),
        Window(8, "egress window", " large openings that offer a secondary exit in case of an emergency", "https://www.wcmanet.org/wp-content/uploads/2020/03/Why-Are-Egress-Windows-So-Essential.jpg"),
        Window(9, "fixed window", "a standard window that is non-operational", "https://image.made-in-china.com/43f34j00giGYoqEBJkbc/Sound-Proof-Aluminum-Fixed-Windows-with-Double-Glazing.jpg"),
        Window(10,"french door window", "window with a door of light construction which has glass panes extending for most of its length", "https://media.istockphoto.com/photos/beautiful-garden-windows-picture-id475805595?k=20&m=475805595&s=612x612&w=0&h=HqGZu_3bXduq70H_fN-RNvPbvaGH0vs-HcAr0Lmd0Js="),
        Window(11,"french door window", "window with a door of light construction which has glass panes extending for most of its length", "https://media.istockphoto.com/photos/beautiful-garden-windows-picture-id475805595?k=20&m=475805595&s=612x612&w=0&h=HqGZu_3bXduq70H_fN-RNvPbvaGH0vs-HcAr0Lmd0Js="),
        Window(12,"french door window", "window with a door of light construction which has glass panes extending for most of its length", "https://media.istockphoto.com/photos/beautiful-garden-windows-picture-id475805595?k=20&m=475805595&s=612x612&w=0&h=HqGZu_3bXduq70H_fN-RNvPbvaGH0vs-HcAr0Lmd0Js="),
        Window(13,"french door window", "window with a door of light construction which has glass panes extending for most of its length", "https://media.istockphoto.com/photos/beautiful-garden-windows-picture-id475805595?k=20&m=475805595&s=612x612&w=0&h=HqGZu_3bXduq70H_fN-RNvPbvaGH0vs-HcAr0Lmd0Js="),
        Window(14,"french door window", "window with a door of light construction which has glass panes extending for most of its length", "https://media.istockphoto.com/photos/beautiful-garden-windows-picture-id475805595?k=20&m=475805595&s=612x612&w=0&h=HqGZu_3bXduq70H_fN-RNvPbvaGH0vs-HcAr0Lmd0Js="),
        Window(15,"french door window", "window with a door of light construction which has glass panes extending for most of its length", "https://media.istockphoto.com/photos/beautiful-garden-windows-picture-id475805595?k=20&m=475805595&s=612x612&w=0&h=HqGZu_3bXduq70H_fN-RNvPbvaGH0vs-HcAr0Lmd0Js="),
        Window(16,"french door window", "window with a door of light construction which has glass panes extending for most of its length", "https://media.istockphoto.com/photos/beautiful-garden-windows-picture-id475805595?k=20&m=475805595&s=612x612&w=0&h=HqGZu_3bXduq70H_fN-RNvPbvaGH0vs-HcAr0Lmd0Js="),
        Window(17,"french door window", "window with a door of light construction which has glass panes extending for most of its length", "https://media.istockphoto.com/photos/beautiful-garden-windows-picture-id475805595?k=20&m=475805595&s=612x612&w=0&h=HqGZu_3bXduq70H_fN-RNvPbvaGH0vs-HcAr0Lmd0Js="),
        Window(18,"french door window", "window with a door of light construction which has glass panes extending for most of its length", "https://media.istockphoto.com/photos/beautiful-garden-windows-picture-id475805595?k=20&m=475805595&s=612x612&w=0&h=HqGZu_3bXduq70H_fN-RNvPbvaGH0vs-HcAr0Lmd0Js="),
        Window(19,"french door window", "window with a door of light construction which has glass panes extending for most of its length", "https://media.istockphoto.com/photos/beautiful-garden-windows-picture-id475805595?k=20&m=475805595&s=612x612&w=0&h=HqGZu_3bXduq70H_fN-RNvPbvaGH0vs-HcAr0Lmd0Js="),
        Window(20,"french door window", "window with a door of light construction which has glass panes extending for most of its length", "https://media.istockphoto.com/photos/beautiful-garden-windows-picture-id475805595?k=20&m=475805595&s=612x612&w=0&h=HqGZu_3bXduq70H_fN-RNvPbvaGH0vs-HcAr0Lmd0Js="),
        Window(21,"french door window", "window with a door of light construction which has glass panes extending for most of its length", "https://media.istockphoto.com/photos/beautiful-garden-windows-picture-id475805595?k=20&m=475805595&s=612x612&w=0&h=HqGZu_3bXduq70H_fN-RNvPbvaGH0vs-HcAr0Lmd0Js="),
    )
}
